//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Craftsmaneer.DataToolUtils.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\v11.0;Initial Catalog=DataDiff;Integrated Security=True")]
        public string txtConnStr_Text {
            get {
                return ((string)(this["txtConnStr_Text"]));
            }
            set {
                this["txtConnStr_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\tfs\\rdb\\projects\\DataTools\\Export")]
        public string txtExportPath_Text {
            get {
                return ((string)(this["txtExportPath_Text"]));
            }
            set {
                this["txtExportPath_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\tfs\\rdb\\projects\\DataTools\\Export")]
        public string txtImportDataTablePath_Text {
            get {
                return ((string)(this["txtImportDataTablePath_Text"]));
            }
            set {
                this["txtImportDataTablePath_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FolderDTC.config")]
        public string txtMasterDataTableSet_Text {
            get {
                return ((string)(this["txtMasterDataTableSet_Text"]));
            }
            set {
                this["txtMasterDataTableSet_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Database_DTC.config")]
        public string txtReplicaDtSet_Text {
            get {
                return ((string)(this["txtReplicaDtSet_Text"]));
            }
            set {
                this["txtReplicaDtSet_Text"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string workspaceRoot {
            get {
                return ((string)(this["workspaceRoot"]));
            }
        }
    }
}
